Repository logfellow/logstash-logback-encoder, pull requests merged in 2023-06, with the labels that each got.

#970 Drop support for logback 1.2
  .github/workflows/build.yml
  README.md
  pom.xml
  src/main/java/net/logstash/logback/composite/AbstractSequenceJsonProvider.java
  src/main/java/net/logstash/logback/composite/loggingevent/LoggingEventFormattedTimestampJsonProvider.java
  src/main/java/net/logstash/logback/composite/loggingevent/LogstashMarkersJsonProvider.java
  src/main/java/net/logstash/logback/composite/loggingevent/TagsJsonProvider.java
  src/main/java/net/logstash/logback/util/LogbackUtils.java
  src/test/java/net/logstash/logback/composite/loggingevent/LoggingEventFormattedTimestampJsonProviderTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/LogstashMarkersJsonProviderTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/SequenceJsonProviderTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/TagsJsonProviderTest.java
  src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
Labels: type/enhancement, warn/behavior-change

#954 Support key values from slf4j's fluent api
  README.md
  src/main/java/net/logstash/logback/LogstashFormatter.java
  src/main/java/net/logstash/logback/composite/loggingevent/KeyValuePairsJsonProvider.java
  src/main/java/net/logstash/logback/composite/loggingevent/LoggingEventJsonProviders.java
  src/main/java/net/logstash/logback/encoder/LogstashEncoder.java
  src/main/java/net/logstash/logback/fieldnames/LogstashFieldNames.java
  src/main/java/net/logstash/logback/layout/LogstashLayout.java
  src/test/java/net/logstash/logback/ConfigurationTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/KeyValuePairsJsonProviderTest.java
  src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
  src/test/resources/logback-test.xml
Labels: type/enhancement

#968 Honor overriden `writeObject` of `JsonGenerator` passed to `setJsonGeneratorDecorator`
  src/main/java/net/logstash/logback/composite/AbstractCompositeJsonFormatter.java
  src/test/java/net/logstash/logback/composite/loggingevent/LoggingEventCompositeJsonFormatterTest.java
Labels: type/bug

#957 Add MDC entry writers to be able to convert values
  README.md
  src/main/java/net/logstash/logback/LogstashFormatter.java
  src/main/java/net/logstash/logback/composite/loggingevent/MdcJsonProvider.java
  src/main/java/net/logstash/logback/composite/loggingevent/mdc/BooleanMdcEntryWriter.java
  src/main/java/net/logstash/logback/composite/loggingevent/mdc/DoubleMdcEntryWriter.java
  src/main/java/net/logstash/logback/composite/loggingevent/mdc/LongMdcEntryWriter.java
  src/main/java/net/logstash/logback/composite/loggingevent/mdc/MdcEntryWriter.java
  src/main/java/net/logstash/logback/encoder/LogstashEncoder.java
  src/main/java/net/logstash/logback/layout/LogstashLayout.java
  src/test/java/net/logstash/logback/ConfigurationTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/MdcJsonProviderTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/mdc/BooleanMdcEntryWriterTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/mdc/DoubleMdcEntryWriterTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/mdc/LongMdcEntryWriterTest.java
  src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
  src/test/resources/logback-test.xml
Labels: type/enhancement
