Repository logfellow/logstash-logback-encoder, pull requests merged in 2024-07, with the labels that each got.

#1024 Fix typo in IllegalArgumentException message
  src/main/java/net/logstash/logback/encoder/LogstashAccessEncoder.java
  src/main/java/net/logstash/logback/encoder/LogstashEncoder.java
  src/main/java/net/logstash/logback/layout/LogstashAccessLayout.java
  src/main/java/net/logstash/logback/layout/LogstashLayout.java
Labels: type/bug

#1027 Add jdk21 to build matrix
  .github/workflows/build.yml
Labels: type/chore

#1028 Upgrade dependencies and maven plugins
  pom.xml
  src/main/java/net/logstash/logback/composite/SequenceJsonProvider.java
  src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
  src/test/java/net/logstash/logback/composite/accessevent/AccessEventNestedJsonProviderTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/LoggingEventNestedJsonProviderTest.java
  src/test/java/net/logstash/logback/util/ThreadLocalHolderTest.java
Labels: type/dependencies

#988 Set AbstractThrowableClassNameJsonProvider.getThrowable as protected
  src/main/java/net/logstash/logback/composite/loggingevent/AbstractThrowableClassNameJsonProvider.java
  src/main/java/net/logstash/logback/composite/loggingevent/ThrowableClassNameJsonProvider.java
  src/main/java/net/logstash/logback/composite/loggingevent/ThrowableRootCauseClassNameJsonProvider.java
Labels: type/enhancement

#974 Add composite MdcEntryWriter to filter MDC keys with regex
  README.md
  src/main/java/net/logstash/logback/composite/loggingevent/mdc/RegexFilteringMdcEntryWriter.java
  src/test/java/net/logstash/logback/ConfigurationTest.java
  src/test/java/net/logstash/logback/composite/loggingevent/mdc/RegexFilteringMdcEntryWriterTest.java
  src/test/resources/logback-test.xml
Labels: type/enhancement

#1029 Update readme for 8.0
  README.md
Labels: type/documentation
